#ifdef KEYNAME
KEYNAME("LBUTTON"        ,0x01)
KEYNAME("RBUTTON"        ,0x02)
KEYNAME("CANCEL"         ,0x03)
KEYNAME("MBUTTON"        ,0x04)
KEYNAME("XBUTTON1"       ,0x05)
KEYNAME("XBUTTON2"       ,0x06)
KEYNAME("BACK"           ,0x08)
KEYNAME("TAB"            ,0x09)
KEYNAME("CLEAR"          ,0x0C)
KEYNAME("RETURN"         ,0x0D)
KEYNAME("SHIFT"          ,0x10)
KEYNAME("CONTROL"        ,0x11)
KEYNAME("MENU"           ,0x12)
KEYNAME("PAUSE"          ,0x13)
KEYNAME("CAPITAL"        ,0x14)
KEYNAME("KANA"           ,0x15)
KEYNAME("HANGEUL"        ,0x15)
KEYNAME("HANGUL"         ,0x15)
KEYNAME("JUNJA"          ,0x17)
KEYNAME("FINAL"          ,0x18)
KEYNAME("HANJA"          ,0x19)
KEYNAME("KANJI"          ,0x19)
KEYNAME("ESCAPE"         ,0x1B)
KEYNAME("CONVERT"        ,0x1C)
KEYNAME("NONCONVERT"     ,0x1D)
KEYNAME("ACCEPT"         ,0x1E)
KEYNAME("MODECHANGE"     ,0x1F)
KEYNAME("SPACE"          ,0x20)
KEYNAME("PRIOR"          ,0x21)
KEYNAME("NEXT"           ,0x22)
KEYNAME("END"            ,0x23)
KEYNAME("HOME"           ,0x24)
KEYNAME("LEFT"           ,0x25)
KEYNAME("UP"             ,0x26)
KEYNAME("RIGHT"          ,0x27)
KEYNAME("DOWN"           ,0x28)
KEYNAME("SELECT"         ,0x29)
KEYNAME("PRINT"          ,0x2A)
KEYNAME("EXECUTE"        ,0x2B)
KEYNAME("SNAPSHOT"       ,0x2C)
KEYNAME("INSERT"         ,0x2D)
KEYNAME("DELETE"         ,0x2E)
KEYNAME("HELP"           ,0x2F)
KEYNAME("0"              ,0x30)
KEYNAME("1"              ,0x31)
KEYNAME("2"              ,0x32)
KEYNAME("3"              ,0x33)
KEYNAME("4"              ,0x34)
KEYNAME("5"              ,0x35)
KEYNAME("6"              ,0x36)
KEYNAME("7"              ,0x37)
KEYNAME("8"              ,0x38)
KEYNAME("9"              ,0x39)
KEYNAME("A"              ,0x41)
KEYNAME("B"              ,0x42)
KEYNAME("C"              ,0x43)
KEYNAME("D"              ,0x44)
KEYNAME("E"              ,0x45)
KEYNAME("F"              ,0x46)
KEYNAME("G"              ,0x47)
KEYNAME("H"              ,0x48)
KEYNAME("I"              ,0x49)
KEYNAME("J"              ,0x4A)
KEYNAME("K"              ,0x4B)
KEYNAME("L"              ,0x4C)
KEYNAME("M"              ,0x4D)
KEYNAME("N"              ,0x4E)
KEYNAME("O"              ,0x4F)
KEYNAME("P"              ,0x50)
KEYNAME("Q"              ,0x51)
KEYNAME("R"              ,0x52)
KEYNAME("S"              ,0x53)
KEYNAME("T"              ,0x54)
KEYNAME("U"              ,0x55)
KEYNAME("V"              ,0x56)
KEYNAME("W"              ,0x57)
KEYNAME("X"              ,0x58)
KEYNAME("Y"              ,0x59)
KEYNAME("Z"              ,0x5A)
KEYNAME("LWIN"           ,0x5B)
KEYNAME("RWIN"           ,0x5C)
KEYNAME("APPS"           ,0x5D)
KEYNAME("SLEEP"          ,0x5F)
KEYNAME("NUMPAD0"        ,0x60)
KEYNAME("NUMPAD1"        ,0x61)
KEYNAME("NUMPAD2"        ,0x62)
KEYNAME("NUMPAD3"        ,0x63)
KEYNAME("NUMPAD4"        ,0x64)
KEYNAME("NUMPAD5"        ,0x65)
KEYNAME("NUMPAD6"        ,0x66)
KEYNAME("NUMPAD7"        ,0x67)
KEYNAME("NUMPAD8"        ,0x68)
KEYNAME("NUMPAD9"        ,0x69)
KEYNAME("MULTIPLY"       ,0x6A)
KEYNAME("ADD"            ,0x6B)
KEYNAME("SEPARATOR"      ,0x6C)
KEYNAME("SUBTRACT"       ,0x6D)
KEYNAME("DECIMAL"        ,0x6E)
KEYNAME("DIVIDE"         ,0x6F)
KEYNAME("F1"             ,0x70)
KEYNAME("F2"             ,0x71)
KEYNAME("F3"             ,0x72)
KEYNAME("F4"             ,0x73)
KEYNAME("F5"             ,0x74)
KEYNAME("F6"             ,0x75)
KEYNAME("F7"             ,0x76)
KEYNAME("F8"             ,0x77)
KEYNAME("F9"             ,0x78)
KEYNAME("F10"            ,0x79)
KEYNAME("F11"            ,0x7A)
KEYNAME("F12"            ,0x7B)
KEYNAME("F13"            ,0x7C)
KEYNAME("F14"            ,0x7D)
KEYNAME("F15"            ,0x7E)
KEYNAME("F16"            ,0x7F)
KEYNAME("F17"            ,0x80)
KEYNAME("F18"            ,0x81)
KEYNAME("F19"            ,0x82)
KEYNAME("F20"            ,0x83)
KEYNAME("F21"            ,0x84)
KEYNAME("F22"            ,0x85)
KEYNAME("F23"            ,0x86)
KEYNAME("F24"            ,0x87)
KEYNAME("NUMLOCK"        ,0x90)
KEYNAME("SCROLL"         ,0x91)
KEYNAME("OEM_NEC_EQUAL"  ,0x92   )// '=' key on numpad
KEYNAME("OEM_FJ_JISHO"   ,0x92   )// 'Dictionary' key
KEYNAME("OEM_FJ_MASSHOU" ,0x93   )// 'Unregister word' key
KEYNAME("OEM_FJ_TOUROKU" ,0x94   )// 'Register word' key
KEYNAME("OEM_FJ_LOYA"    ,0x95   )// 'Left OYAYUBI' key
KEYNAME("OEM_FJ_ROYA"    ,0x96   )// 'Right OYAYUBI' key
KEYNAME("BROWSER_BACK"        ,0xA6)
KEYNAME("BROWSER_FORWARD"     ,0xA7)
KEYNAME("BROWSER_REFRESH"     ,0xA8)
KEYNAME("BROWSER_STOP"        ,0xA9)
KEYNAME("BROWSER_SEARCH"      ,0xAA)
KEYNAME("BROWSER_FAVORITES"   ,0xAB)
KEYNAME("BROWSER_HOME"        ,0xAC)
KEYNAME("VOLUME_MUTE"         ,0xAD)
KEYNAME("VOLUME_DOWN"         ,0xAE)
KEYNAME("VOLUME_UP"           ,0xAF)
KEYNAME("MEDIA_NEXT_TRACK"    ,0xB0)
KEYNAME("MEDIA_PREV_TRACK"    ,0xB1)
KEYNAME("MEDIA_STOP"          ,0xB2)
KEYNAME("MEDIA_PLAY_PAUSE"    ,0xB3)
KEYNAME("LAUNCH_MAIL"         ,0xB4)
KEYNAME("LAUNCH_MEDIA_SELECT" ,0xB5)
KEYNAME("LAUNCH_APP1"         ,0xB6)
KEYNAME("LAUNCH_APP2"         ,0xB7)
KEYNAME("OEM_1"          ,0xBA   )// ';:' for US
KEYNAME("OEM_PLUS"       ,0xBB   )// '+' any country
KEYNAME("OEM_COMMA"      ,0xBC   )// ',' any country
KEYNAME("OEM_MINUS"      ,0xBD   )// '-' any country
KEYNAME("OEM_PERIOD"     ,0xBE   )// '.' any country
KEYNAME("OEM_2"          ,0xBF   )// '/?' for US
KEYNAME("OEM_3"          ,0xC0   )// '`~' for US
KEYNAME("OEM_4"          ,0xDB  )//  '[{' for US
KEYNAME("OEM_5"          ,0xDC  )//  '\|' for US
KEYNAME("OEM_6"          ,0xDD  )//  ']}' for US
KEYNAME("OEM_7"          ,0xDE  )//  ''"' for US
KEYNAME("OEM_8"          ,0xDF)
KEYNAME("OEM_AX"         ,0xE1  )//  'AX' key on Japanese AX kbd
KEYNAME("OEM_102"        ,0xE2  )//  "<>" or "\|" on RT 102-key kbd.
KEYNAME("ICO_HELP"       ,0xE3  )//  Help key on ICO
KEYNAME("ICO_00"         ,0xE4  )//  00 key on ICO
KEYNAME("PROCESSKEY"     ,0xE5)
KEYNAME("ICO_CLEAR"      ,0xE6)
KEYNAME("PACKET"         ,0xE7)
KEYNAME("OEM_RESET"      ,0xE9)
KEYNAME("OEM_JUMP"       ,0xEA)
KEYNAME("OEM_PA1"        ,0xEB)
KEYNAME("OEM_PA2"        ,0xEC)
KEYNAME("OEM_PA3"        ,0xED)
KEYNAME("OEM_WSCTRL"     ,0xEE)
KEYNAME("OEM_CUSEL"      ,0xEF)
KEYNAME("OEM_ATTN"       ,0xF0)
KEYNAME("OEM_FINISH"     ,0xF1)
KEYNAME("OEM_COPY"       ,0xF2)
KEYNAME("OEM_AUTO"       ,0xF3)
KEYNAME("OEM_ENLW"       ,0xF4)
KEYNAME("OEM_BACKTAB"    ,0xF5)
KEYNAME("ATTN"           ,0xF6)
KEYNAME("CRSEL"          ,0xF7)
KEYNAME("EXSEL"          ,0xF8)
KEYNAME("EREOF"          ,0xF9)
KEYNAME("PLAY"           ,0xFA)
KEYNAME("ZOOM"           ,0xFB)
KEYNAME("NONAME"         ,0xFC)
KEYNAME("PA1"            ,0xFD)
KEYNAME("OEM_CLEAR"      ,0xFE)
#undef KEYNAME
#endif
